name: Build Docs

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'

env:
  COMMIT_EMAIL: ben.jeffery.well+adminbot@gmail.com
  DOXYGEN: true
  MAKE_TARGET: -C python
  OWNER: tskit-dev
  REPO: tskit
  REQUIREMENTS: python/requirements/CI-docs/requirements.txt
  APTGET: doxygen

jobs:
  build-deploy-docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install apt deps
        if: env.APTGET
        run: sudo apt-get install -y ${{env.APTGET}}

      - uses: actions/cache@v3
        id: venv-cache
        with:
          path: venv
          key: docs-venv-v5-${{ hashFiles(env.REQUIREMENTS) }}

      - name: Create venv and install deps (one by one to avoid conflict errors)
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip wheel
          pip install -r ${{env.REQUIREMENTS}}          

      - name: Build C module
        if: env.MAKE_TARGET
        run: |
          . venv/bin/activate
          make $MAKE_TARGET

      - name: Build Docs
        run: |
          . venv/bin/activate
          make -C docs

      - name: Trigger docs site rebuild
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST https://api.github.com/repos/tskit-dev/tskit-site/dispatches \
                    -H 'Accept: application/vnd.github.everest-preview+json' \
                    -u AdminBot-tskit:${{ secrets.ADMINBOT_TOKEN }} \
                    --data '{"event_type":"build-docs"}'
